import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { Radar, Wind } from 'lucide-react'
import { useAuth } from '../context/AuthContext'

export default function Login() {
	const { signIn } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
	const submit = async (event) => { event.preventDefault(); setError(''); setLoading(true); try { const user = await signIn(form); navigate(user.role === 'admin' ? '/admin' : location.state?.from || '/dashboard') } catch (err) { setError(err.response?.data?.detail || err.message || 'Unable to sign in') } finally { setLoading(false) } }
	return <div className="auth"><section className="auth-info"><div className="brand"><span className="brand-mark"><Wind size={18} /></span>VargMinds</div><h1>Weather intelligence before the storm.</h1><p className="muted">Personalized early warnings for the decisions that matter.</p><Radar size={150} color="#63d9cf" /></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><span className="eyebrow">Welcome back</span><h2>Sign in</h2><p className="muted">Access your local weather intelligence.</p><div className="field"><label htmlFor="email">Email</label><input id="email" type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></div><div className="field"><label htmlFor="password">Password</label><input id="password" type="password" required value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></div>{error && <p className="error">{error}</p>}<button className="primary" disabled={loading}>{loading ? 'Signing in...' : 'Sign in'}</button><p className="muted">New here? <Link to="/register" style={{ color: 'var(--accent)' }}>Create an account</Link></p></form></section></div>
}
