import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { Eye, EyeOff, Radar, Wind } from 'lucide-react'
import { useAuth } from '../context/AuthContext'

export default function Login() {
	const { signIn } = useAuth(); const navigate = useNavigate(); const location = useLocation()
	const [form, setForm] = useState({ email: '', password: '' }); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
	const submit = async (event) => { event.preventDefault(); setError(''); if (!form.email || !form.password) return setError('Enter your email and password.')
		setLoading(true); try { const user = await signIn(form); navigate(user.role === 'admin' ? '/admin' : location.state?.from || '/dashboard') } catch (requestError) { setError(requestError.response?.data?.detail || requestError.message || 'Unable to sign in right now.') } finally { setLoading(false) }
	}
	return <div className="auth-layout"><section className="auth-visual"><div className="brand"><span className="brand-mark"><Wind size={19} /></span>VargMinds</div><h1>Weather intelligence that arrives before the storm.</h1><p>Personalized early warnings for the decisions that matter, powered by live weather signals and thoughtful recommendations.</p><Radar size={150} strokeWidth={.7} color="#55e1d0" /></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><span className="eyebrow">Welcome back</span><h2>Sign in</h2><p className="muted">Access your local weather intelligence.</p><div className="form-field"><label htmlFor="email">Email address</label><input id="email" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} autoComplete="email" /></div><div className="form-field"><label htmlFor="password">Password</label><div style={{ position: 'relative' }}><input id="password" type={showPassword ? 'text' : 'password'} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} autoComplete="current-password" style={{ paddingRight: 46 }} /><button type="button" className="icon-button" aria-label="Toggle password visibility" onClick={() => setShowPassword(!showPassword)} style={{ position: 'absolute', right: 5, top: 5, border: 0 }}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></div>{error && <p className="error">{error}</p>}<button className="primary-button" disabled={loading}>{loading ? 'Signing in...' : 'Sign in'}</button><p className="muted" style={{ textAlign: 'center', marginTop: 22 }}>New to VargMinds? <Link className="auth-link" to="/register">Create an account</Link></p></form></section></div>
}
