import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Wind } from 'lucide-react'
import { register } from '../services/auth'

export default function Register() {
	const navigate = useNavigate(); const [form, setForm] = useState({ full_name: '', email: '', password: '', confirm_password: '', designation: 'General User', location: '' }); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [loading, setLoading] = useState(false)
	const update = (key) => (event) => setForm({ ...form, [key]: event.target.value })
	const submit = async (event) => { event.preventDefault(); setError(''); if (Object.values(form).some((value) => !value)) return setError('Complete every field to continue.'); if (form.password !== form.confirm_password) return setError('Passwords do not match.'); setLoading(true); try { await register(form); setSuccess('Your account was created. Redirecting to sign in...'); setTimeout(() => navigate('/login'), 900) } catch (requestError) { setError(requestError.response?.data?.detail || 'Unable to create your account.') } finally { setLoading(false) } }
	return <div className="auth-layout"><section className="auth-visual"><div className="brand"><span className="brand-mark"><Wind size={19} /></span>VargMinds</div><h1>Build a clearer picture of your day outside.</h1><p>Choose your context and location so future alerts can meet you where you are.</p></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><span className="eyebrow">Get started</span><h2>Create account</h2><p className="muted">Your role is assigned by the platform.</p><div className="form-field"><label htmlFor="full_name">Full name</label><input id="full_name" value={form.full_name} onChange={update('full_name')} /></div><div className="form-field"><label htmlFor="email">Email address</label><input id="email" type="email" value={form.email} onChange={update('email')} /></div><div className="grid" style={{ gridTemplateColumns: '1fr 1fr' }}><div className="form-field"><label htmlFor="designation">Designation</label><select id="designation" value={form.designation} onChange={update('designation')}><option>General User</option><option>Farmer</option><option>Student</option><option>Fisherman</option><option>Driver</option><option>Outdoor Worker</option></select></div><div className="form-field"><label htmlFor="location">Location</label><input id="location" value={form.location} onChange={update('location')} placeholder="City" /></div></div><div className="form-field"><label htmlFor="password">Password</label><input id="password" type="password" value={form.password} onChange={update('password')} /></div><div className="form-field"><label htmlFor="confirm_password">Confirm password</label><input id="confirm_password" type="password" value={form.confirm_password} onChange={update('confirm_password')} /></div>{error && <p className="error">{error}</p>}{success && <p style={{ color: '#55e1d0' }}>{success}</p>}<button className="primary-button" disabled={loading}>{loading ? 'Creating account...' : 'Create account'}</button><p className="muted" style={{ textAlign: 'center', marginTop: 22 }}>Already registered? <Link className="auth-link" to="/login">Sign in</Link></p></form></section></div>
}
