import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Wind } from 'lucide-react'
import { register } from '../services/auth'

export default function Register() {
	const navigate = useNavigate(); const [form, setForm] = useState({ full_name: '', email: '', password: '', designation: 'General User', location: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
	const update = (key) => (e) => setForm({ ...form, [key]: e.target.value })
	const submit = async (event) => { event.preventDefault(); setError(''); setLoading(true); try { await register(form); navigate('/login') } catch (err) { setError(err.response?.data?.detail || 'Unable to create account') } finally { setLoading(false) } }
	return <div className="auth"><section className="auth-info"><div className="brand"><span className="brand-mark"><Wind size={18} /></span>VargMinds</div><h1>Your day outside, made clearer.</h1><p className="muted">Create a profile so weather warnings can reflect your context.</p></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><span className="eyebrow">Get started</span><h2>Create account</h2><div className="field"><label htmlFor="full_name">Full name</label><input id="full_name" required value={form.full_name} onChange={update('full_name')} /></div><div className="field"><label htmlFor="email">Email</label><input id="email" type="email" required value={form.email} onChange={update('email')} /></div><div className="field"><label htmlFor="designation">Designation</label><select id="designation" value={form.designation} onChange={update('designation')}><option>General User</option><option>Farmer</option><option>Student</option><option>Fisherman</option><option>Driver</option><option>Outdoor Worker</option></select></div><div className="field"><label htmlFor="location">Location</label><input id="location" required value={form.location} onChange={update('location')} placeholder="City or region" /></div><div className="field"><label htmlFor="password">Password</label><input id="password" type="password" minLength="8" required value={form.password} onChange={update('password')} /></div>{error && <p className="error">{error}</p>}<button className="primary" disabled={loading}>{loading ? 'Creating...' : 'Create account'}</button><p className="muted">Already registered? <Link to="/login" style={{ color: 'var(--accent)' }}>Sign in</Link></p></form></section></div>
}
