import { CloudRain, Droplets, Eye, Gauge, MapPin, Navigation, Sun, Thermometer, Umbrella, Wind } from 'lucide-react'
import { useAuth } from '../context/AuthContext'

const fallbackForecast = [
	['Today', Sun, '32°', '24°'], ['Tue', CloudRain, '30°', '23°'], ['Wed', CloudRain, '29°', '22°'], ['Thu', Sun, '31°', '23°'], ['Fri', Sun, '33°', '25°'],
]

function Metric({ icon: Icon, label, value }) { return <div className="panel metric"><Icon size={19} /><div className="metric-label">{label}</div><div className="metric-value">{value}</div></div> }

export default function UserDashboard() {
	const { user } = useAuth(); const name = user?.name || user?.full_name || 'there'; const location = user?.location || 'Your selected location'
	return <><div className="dashboard-heading"><div><span className="eyebrow">Wednesday, 09 September 2026</span><h1>Good morning, {name.split(' ')[0]}.</h1><p>Here is the atmospheric picture around {location}.</p></div><span className="date-pill"><MapPin size={15} />{location}</span></div><div className="grid grid-main"><section className="panel weather-hero"><div className="weather-location"><MapPin size={14} style={{ verticalAlign: 'middle' }} /> {location}</div><div className="temperature">32°</div><div className="condition">Sunny with light haze</div><div className="hero-bottom"><span>Feels like<strong>35°</strong></span><span>High / low<strong>34° / 24°</strong></span><span>Updated<strong>Just now</strong></span></div></section><section className="panel panel-pad alert critical"><div className="section-head"><h2>Active alert</h2><span className="badge badge-high">High</span></div><div className="alert-title"><h3>Heat advisory</h3><Thermometer size={24} color="#ff9e81" /></div><p>Elevated heat is expected through the afternoon. Limit prolonged outdoor activity and stay hydrated.</p><strong style={{ color: '#ffd2a0', fontSize: 13 }}>Recommended action</strong><p>Schedule demanding outdoor work before midday and keep water accessible.</p></section></div><div className="grid metric-grid"><Metric icon={Droplets} label="Humidity" value="68%" /><Metric icon={Wind} label="Wind" value="14 km/h" /><Metric icon={Umbrella} label="Precipitation" value="10%" /><Metric icon={Eye} label="Visibility" value="8.4 km" /></div><section className="panel panel-pad"><div className="section-head"><h2>Five-day outlook</h2><span className="muted" style={{ fontSize: 13 }}>Live forecast</span></div><div className="forecast-row">{fallbackForecast.map(([day, Icon, high, low]) => <div className="forecast-item" key={day}><strong>{day}</strong><Icon size={22} /><span>{high} / {low}</span></div>)}</div></section><div className="grid grid-main" style={{ marginTop: 18 }}><section className="panel panel-pad"><div className="section-head"><h2>Why this matters</h2><Gauge size={19} color="#55e1d0" /></div><p className="muted" style={{ lineHeight: 1.7 }}>Heat can build quickly in exposed areas. Your weather profile will use your designation and location to make future warnings more relevant.</p><div className="date-pill"><Navigation size={14} /> Personalized for {user?.designation || 'General User'}</div></section><section className="panel panel-pad"><div className="section-head"><h2>Next update</h2><CloudRain size={19} color="#62b6ff" /></div><p className="muted">Your weather feed will refresh when connected to the backend service.</p><strong style={{ color: '#e9f2ff' }}>Stay aware. Stay ready.</strong></section></div></>
}
