import { useEffect, useState } from 'react'
import { CloudRain, Droplets, MapPin, Thermometer, Wind } from 'lucide-react'
import api from '../services/api'
import { useAuth } from '../context/AuthContext'

export default function UserDashboard() {
	const { user } = useAuth(); const [weather, setWeather] = useState(null); const [alerts, setAlerts] = useState([]); const [insight, setInsight] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
	useEffect(() => { const location = user?.location || 'Andhra Pradesh'; Promise.all([api.get('/weather/current', { params: { location } }), api.get('/alerts/'), api.post('/weather/ai-analysis', null, { params: { location } })]).then(([weatherResponse, alertResponse, insightResponse]) => { setWeather(weatherResponse.data); setAlerts(alertResponse.data); setInsight(insightResponse.data.ai_insight) }).catch((err) => setError(err.response?.data?.detail || 'Unable to load live weather data.')).finally(() => setLoading(false)) }, [user?.location])
	if (loading) return <div className="panel"><p>Fetching latest weather...</p></div>; if (error) return <div className="panel"><p className="error">{error}</p><button className="icon-button" onClick={() => window.location.reload()}>Retry</button></div>
	const current = weather?.weather || {}; const alert = alerts[0] || weather?.alert
	return <><div className="heading"><div><span className="eyebrow">Personal weather intelligence</span><h1>Good morning, {user?.name?.split(' ')[0] || 'there'}.</h1><p className="muted">Live conditions around {current.location}.</p></div><span className="pill"><MapPin size={14} /> {current.location}</span></div><div className="grid two"><section className="panel hero"><p className="muted"><MapPin size={14} /> {current.location}</p><div className="temperature">{current.temperature ?? '--'}°</div><p className="muted">Weather code {current.weather_code ?? '--'} · Updated {current.time || 'now'}</p></section>{alert ? <section className="panel alert"><div style={{ display: 'flex', justifyContent: 'space-between' }}><h2>{alert.title || alert.message}</h2><span className="badge">{alert.severity || 'INFO'}</span></div><p className="muted">{alert.description || alert.message}</p><strong>Recommended action</strong><p className="muted">Review local conditions and avoid unnecessary exposure during severe weather.</p></section> : <section className="panel"><h2>Active alerts</h2><p className="muted">No active alerts for this location.</p></section>}</div><div className="grid metrics"><Metric icon={Wind} label="Wind" value={`${current.wind_speed ?? '--'} km/h`} /><Metric icon={Thermometer} label="Weather code" value={current.weather_code ?? '--'} /><Metric icon={Droplets} label="Humidity" value="Live API field pending" /><Metric icon={CloudRain} label="AI status" value={insight?.risk_level || 'Available'} /></div><section className="panel"><h2>Why this matters</h2><p className="muted">{insight?.summary || insight?.alert_message || 'AI analysis is unavailable right now, but live weather remains available.'}</p>{insight?.recommended_actions?.length > 0 && <ul>{insight.recommended_actions.map((action) => <li key={action}>{action}</li>)}</ul>}</section></>
}
function Metric({ icon: Icon, label, value }) { return <div className="panel"><Icon size={18} color="var(--accent)" /><div className="metric-label">{label}</div><div className="metric-value">{value}</div></div> }
